/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CotSheetCostingPanel.java
 *
 * Created on Apr 25, 2013, 3:17:08 AM
 */
package view;

import celcius.Config;
import excel.ItemSummaryObject;
import excel.QuationObject;
import excel.SummaryObject;
import java.awt.EventQueue;
import java.text.DecimalFormat;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.CotSheetLogic;
import ui.helpers.ComboBoxRenderer;
import viewmodels.CotSheetViewModel;

/**
 *
 * @author naka
 */
public class CotSheetCostingPanel extends javax.swing.JPanel {

    /**
     * Creates new form CotSheetCostingPanel
     */
    public CotSheetCostingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cotSheetCostingPanel = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        cotSheetMaterialTypeCombo = new javax.swing.JComboBox();
        cotSheetSizeCombo = new javax.swing.JComboBox();
        cotSheetFabricWastage = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        cotSheetSizeLable = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        cotSheetCustomPanel = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        cotSheetCustomWidth = new javax.swing.JTextField();
        cotSheetCustomHeight = new javax.swing.JTextField();
        cotSheetIncludeLable = new javax.swing.JRadioButton();
        cotSheetIncludeTag = new javax.swing.JRadioButton();
        cotSheetIncludePEBag = new javax.swing.JRadioButton();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        cotSheetTaffateWastage = new javax.swing.JTextField();
        cotSheetPaddingWastage = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        cotSheetPaddingTypeCombo = new javax.swing.JComboBox();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        cotSheetWidthQuiltingShrinkage = new javax.swing.JTextField();
        cotSheetHeightQuiltiingShrinkage = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        cotSheetTaffataTypeCombo = new javax.swing.JComboBox();
        cotSheetSubmitButton = new javax.swing.JButton();
        cotSheetUseCustom = new javax.swing.JRadioButton();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        cotSheetTaxField = new javax.swing.JTextField();
        jLabel307 = new javax.swing.JLabel();
        jLabel308 = new javax.swing.JLabel();
        cotSheetsMarginField = new javax.swing.JTextField();
        jLabel309 = new javax.swing.JLabel();
        cotSheetOtherCostVal = new javax.swing.JTextField();
        jLabel310 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        cotSheetCPUPanel = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        cotSheetLabourCost = new javax.swing.JLabel();
        cotSheetPEBagCost = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        cotSheetTotalMaterialCost = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        cotSheetFabricCost = new javax.swing.JLabel();
        cotSheetThreadCost = new javax.swing.JLabel();
        cotSheetLableCost = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        cotSheetPaddingCost = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        cotSheetTaffataCost = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        cotSheetToatalCost = new javax.swing.JLabel();
        cotSheetElasticCost = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        cotSheetTagCost = new javax.swing.JLabel();
        cotSheetPOH = new javax.swing.JLabel();
        jLabel337 = new javax.swing.JLabel();
        jLabel338 = new javax.swing.JLabel();
        jLabel339 = new javax.swing.JLabel();
        cotSheetNetSellingPrice = new javax.swing.JLabel();
        cotSheetGrossSellingPrice = new javax.swing.JLabel();
        cotSheetTaxes = new javax.swing.JLabel();
        cotSheetExportButton = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        cotSheetTafffataCutWidth = new javax.swing.JLabel();
        cotSheetSMVValue = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        cotSheetFabricPaddingCutWidth = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        cotSheetTaffataCutHeight = new javax.swing.JLabel();
        cotSheetFabricPaddingCutHeight = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();

        cotSheetCostingPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        cotSheetCostingPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel119.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel119.setText("Cot Sheets Costing");

        jLabel121.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel121.setText("Select Fabric Type:");

        cotSheetMaterialTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetMaterialTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getMaterialTypes()));
        cotSheetMaterialTypeCombo.setRenderer(new ComboBoxRenderer(CotSheetLogic.getMaterialTypes()));

        cotSheetSizeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getCotSheetizes()));
        cotSheetSizeCombo.setRenderer(new ComboBoxRenderer(CotSheetLogic.getCotSheetizes()));
        cotSheetSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetSizeComboActionPerformed(evt);
            }
        });

        cotSheetFabricWastage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetFabricWastage.setText("3");
        cotSheetFabricWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetFabricWastageActionPerformed(evt);
            }
        });

        jLabel122.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel122.setText("%");

        cotSheetSizeLable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetSizeLable.setText("Select Size:");

        jLabel124.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel124.setText("Fabric Wastage:");

        jLabel125.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel125.setText("Width (inches) :");

        jLabel126.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel126.setText("Height (inches):");

        cotSheetCustomWidth.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        cotSheetCustomHeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        cotSheetIncludeLable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetIncludeLable.setText("Include Lable");

        cotSheetIncludeTag.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetIncludeTag.setText("Include Tag");

        cotSheetIncludePEBag.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetIncludePEBag.setText("Include PE Bag");

        javax.swing.GroupLayout cotSheetCustomPanelLayout = new javax.swing.GroupLayout(cotSheetCustomPanel);
        cotSheetCustomPanel.setLayout(cotSheetCustomPanelLayout);
        cotSheetCustomPanelLayout.setHorizontalGroup(
            cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotSheetIncludeTag)
                    .addComponent(cotSheetIncludePEBag)
                    .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                        .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel126)
                            .addComponent(jLabel125))
                        .addGap(122, 122, 122)
                        .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                                .addComponent(cotSheetCustomWidth)
                                .addGap(11, 11, 11))
                            .addComponent(cotSheetCustomHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cotSheetIncludeLable))
                .addGap(93, 93, 93))
        );
        cotSheetCustomPanelLayout.setVerticalGroup(
            cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel125)
                    .addComponent(cotSheetCustomWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel126)
                    .addComponent(cotSheetCustomHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetIncludeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetIncludeTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetIncludePEBag)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel127.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel127.setText("Taffata Wastage:");

        jLabel128.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel128.setText("Padding Wastage:");

        cotSheetTaffateWastage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTaffateWastage.setText("3");
        cotSheetTaffateWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetTaffateWastageActionPerformed(evt);
            }
        });

        cotSheetPaddingWastage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetPaddingWastage.setText("3");
        cotSheetPaddingWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetPaddingWastageActionPerformed(evt);
            }
        });

        jLabel129.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel129.setText("%");

        jLabel130.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel130.setText("%");

        jLabel131.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel131.setText("Select Padding Type:");

        cotSheetPaddingTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetPaddingTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getPaddingTypes()));
        cotSheetPaddingTypeCombo.setRenderer(new ComboBoxRenderer(CotSheetLogic.getPaddingTypes()));

        jLabel132.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel132.setText("Width Quilting Shrinkage:");

        jLabel133.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel133.setText("Height Quilting Shrinkage:");

        cotSheetWidthQuiltingShrinkage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetWidthQuiltingShrinkage.setText("8");
        cotSheetWidthQuiltingShrinkage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetWidthQuiltingShrinkageActionPerformed(evt);
            }
        });

        cotSheetHeightQuiltiingShrinkage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetHeightQuiltiingShrinkage.setText("3");
        cotSheetHeightQuiltiingShrinkage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetHeightQuiltiingShrinkageActionPerformed(evt);
            }
        });

        jLabel134.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel134.setText("%");

        jLabel135.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel135.setText("%");

        jLabel136.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel136.setText("Select Taffata Type:");

        cotSheetTaffataTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTaffataTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getTaffataTypes()));
        cotSheetTaffataTypeCombo.setRenderer(new ComboBoxRenderer(CotSheetLogic.getTaffataTypes()));

        cotSheetSubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetSubmitButton.setText("Find Cost Per Unit");
        cotSheetSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetSubmitButtonActionPerformed(evt);
            }
        });

        cotSheetUseCustom.setBackground(new java.awt.Color(204, 204, 204));
        cotSheetUseCustom.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetUseCustom.setText("Use Custom Sizes");
        cotSheetUseCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetUseCustomActionPerformed(evt);
            }
        });

        jLabel305.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel305.setText("Margin:");

        jLabel306.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel306.setText("Taxes:");

        cotSheetTaxField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTaxField.setText(Config.taxesRate);

        jLabel307.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel307.setText("%");

        jLabel308.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel308.setText("%");

        cotSheetsMarginField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetsMarginField.setText(Config.profitMargin);

        jLabel309.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel309.setText("Other costs:");

        cotSheetOtherCostVal.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetOtherCostVal.setText("0.0");
        cotSheetTaxField.setText(Config.taxesRate);

        jLabel310.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel310.setText("Quantity");

        quantity.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        quantity.setText("1");
        cotSheetTaxField.setText(Config.taxesRate);

        javax.swing.GroupLayout cotSheetCostingPanelLayout = new javax.swing.GroupLayout(cotSheetCostingPanel);
        cotSheetCostingPanel.setLayout(cotSheetCostingPanelLayout);
        cotSheetCostingPanelLayout.setHorizontalGroup(
            cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel306)
                                    .addComponent(jLabel305)
                                    .addComponent(jLabel309))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                            .addComponent(cotSheetTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel307))
                                        .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                            .addComponent(cotSheetsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel308)))
                                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                        .addComponent(cotSheetOtherCostVal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))))
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel310)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(153, 153, 153))
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cotSheetCustomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel128)
                                    .addComponent(jLabel127)
                                    .addComponent(jLabel124)
                                    .addComponent(jLabel133)
                                    .addComponent(jLabel132)
                                    .addComponent(jLabel136)
                                    .addComponent(jLabel131)
                                    .addComponent(cotSheetSizeLable)
                                    .addComponent(jLabel121)
                                    .addComponent(cotSheetUseCustom))
                                .addGap(70, 70, 70)
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cotSheetPaddingTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cotSheetSizeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cotSheetMaterialTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetPaddingWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel130))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetTaffateWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel129))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetHeightQuiltiingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel135))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetWidthQuiltingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel134))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel122)))
                                        .addGap(158, 158, 158))
                                    .addComponent(cotSheetTaffataTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(47, 47, 47))))
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel119))
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(cotSheetSubmitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cotSheetCostingPanelLayout.setVerticalGroup(
            cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel119)
                .addGap(18, 18, 18)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetMaterialTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cotSheetSizeLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetPaddingTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel131))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetTaffataTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136))
                .addGap(11, 11, 11)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel134)
                    .addComponent(cotSheetWidthQuiltingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cotSheetHeightQuiltiingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135)
                    .addComponent(jLabel133))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel122)
                    .addComponent(cotSheetFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel124))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel129)
                    .addComponent(cotSheetTaffateWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel127))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel128)
                    .addComponent(cotSheetPaddingWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel130))
                .addGap(23, 23, 23)
                .addComponent(cotSheetUseCustom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetCustomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel305)
                    .addComponent(cotSheetsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel308))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel307)
                    .addComponent(cotSheetTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel306))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetOtherCostVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel309))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel310))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetSubmitButton))
        );

        cotSheetCustomPanel.setVisible(false);

        jLabel143.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel143.setText("Labour Cost:");

        cotSheetLabourCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetLabourCost.setText("0.00");

        cotSheetPEBagCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetPEBagCost.setText("0.00");

        jLabel139.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel139.setText("Lable Cost:");

        cotSheetTotalMaterialCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cotSheetTotalMaterialCost.setText("0.00");

        jLabel137.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel137.setText("Fabric Cost:");

        cotSheetFabricCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetFabricCost.setText("0.00");

        cotSheetThreadCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetThreadCost.setText("0.00");

        cotSheetLableCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetLableCost.setText("0.00");

        jLabel140.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel140.setText("Tag Cost:");

        jLabel151.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel151.setText("Total Material Cost");

        jLabel150.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel150.setText("Elastic Cost: ");

        cotSheetPaddingCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetPaddingCost.setText("0.00");

        jLabel141.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel141.setText("PE Bag Cost:");

        cotSheetTaffataCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTaffataCost.setText("0.00");

        jLabel144.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel144.setText("Toatal Cost Per Unit:");

        jLabel142.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel142.setText("POH:");

        jLabel153.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel153.setText("Padding Cost:");

        jLabel154.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel154.setText("Taffata Cost:");

        jLabel145.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel145.setText("Cost Per Unit");

        cotSheetToatalCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cotSheetToatalCost.setText("0.00");

        cotSheetElasticCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetElasticCost.setText("0.00");

        jLabel138.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel138.setText("Thread Cost:");

        cotSheetTagCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTagCost.setText("0.00");

        cotSheetPOH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetPOH.setText("0.00");

        jLabel337.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel337.setText("Net Selling Price:");

        jLabel338.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel338.setText("Taxes:");

        jLabel339.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel339.setText("Gross Selling Price:");

        cotSheetNetSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cotSheetNetSellingPrice.setText("0.00");

        cotSheetGrossSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cotSheetGrossSellingPrice.setText("0.00");

        cotSheetTaxes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cotSheetTaxes.setText("0.00");

        cotSheetExportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/export.png"))); // NOI18N
        cotSheetExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetExportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addComponent(cotSheetExportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel145))
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel339)
                            .addComponent(jLabel338)
                            .addComponent(jLabel337)
                            .addComponent(jLabel144)
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel154)
                                    .addComponent(jLabel140)
                                    .addComponent(jLabel153)
                                    .addComponent(jLabel139)
                                    .addComponent(jLabel151)
                                    .addComponent(jLabel150)
                                    .addComponent(jLabel141)
                                    .addComponent(jLabel138)
                                    .addComponent(jLabel137)
                                    .addComponent(jLabel143)
                                    .addComponent(jLabel142))
                                .addGap(229, 229, 229)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cotSheetTotalMaterialCost)
                                    .addComponent(cotSheetElasticCost)
                                    .addComponent(cotSheetTagCost)
                                    .addComponent(cotSheetLableCost)
                                    .addComponent(cotSheetThreadCost)
                                    .addComponent(cotSheetFabricCost)
                                    .addComponent(cotSheetTaffataCost)
                                    .addComponent(cotSheetPaddingCost)
                                    .addComponent(cotSheetPEBagCost)
                                    .addComponent(cotSheetToatalCost)
                                    .addComponent(cotSheetLabourCost)
                                    .addComponent(cotSheetPOH)
                                    .addComponent(cotSheetNetSellingPrice)
                                    .addComponent(cotSheetGrossSellingPrice)
                                    .addComponent(cotSheetTaxes))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotSheetExportButton)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel31Layout.createSequentialGroup()
                                    .addComponent(cotSheetFabricCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetPaddingCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetTaffataCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetThreadCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetLableCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetTagCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetElasticCost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cotSheetPEBagCost)
                                    .addGap(18, 18, 18)
                                    .addComponent(cotSheetTotalMaterialCost)
                                    .addGap(18, 18, 18)
                                    .addComponent(cotSheetPOH))
                                .addGroup(jPanel31Layout.createSequentialGroup()
                                    .addComponent(jLabel137)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel153)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel154)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel138)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel139)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel140)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel150)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel141)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel151)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel142)))
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel143)
                                    .addComponent(cotSheetLabourCost))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel144)
                                    .addComponent(cotSheetToatalCost))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel337)
                            .addComponent(cotSheetNetSellingPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel338)
                            .addComponent(cotSheetTaxes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel339)
                            .addComponent(cotSheetGrossSellingPrice))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        cotSheetTafffataCutWidth.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTafffataCutWidth.setText("0.00");

        cotSheetSMVValue.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetSMVValue.setText("0.00");

        jLabel148.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel148.setText("SMV Value:");

        jLabel146.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel146.setText("Fabric/Padding Cutting Width:");

        jLabel156.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel156.setText("Taffata Cutting Height:");

        cotSheetFabricPaddingCutWidth.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetFabricPaddingCutWidth.setText("0.00");

        jLabel149.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel149.setText("Production Parameters");

        jLabel155.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel155.setText("Taffata Cutting Width:");

        cotSheetTaffataCutHeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetTaffataCutHeight.setText("0.00");

        cotSheetFabricPaddingCutHeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cotSheetFabricPaddingCutHeight.setText("0.00");

        jLabel147.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel147.setText("Fabric/Padding Cutting Height:");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel156)
                    .addComponent(jLabel147)
                    .addComponent(jLabel146)
                    .addComponent(jLabel155)
                    .addComponent(jLabel148))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotSheetTafffataCutWidth, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetTaffataCutHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetSMVValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetFabricPaddingCutHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetFabricPaddingCutWidth, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel149)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel149, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(cotSheetFabricPaddingCutWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetFabricPaddingCutHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetTafffataCutWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetTaffataCutHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetSMVValue))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel146)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel147)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel155)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel156)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel148)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cotSheetCPUPanelLayout = new javax.swing.GroupLayout(cotSheetCPUPanel);
        cotSheetCPUPanel.setLayout(cotSheetCPUPanelLayout);
        cotSheetCPUPanelLayout.setHorizontalGroup(
            cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cotSheetCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        cotSheetCPUPanelLayout.setVerticalGroup(
            cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cotSheetCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cotSheetCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cotSheetCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cotSheetCPUPanel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void cotSheetSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetSizeComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetSizeComboActionPerformed

    private void cotSheetFabricWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetFabricWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetFabricWastageActionPerformed

    private void cotSheetTaffateWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetTaffateWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetTaffateWastageActionPerformed

    private void cotSheetPaddingWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetPaddingWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetPaddingWastageActionPerformed

    private void cotSheetWidthQuiltingShrinkageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetWidthQuiltingShrinkageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetWidthQuiltingShrinkageActionPerformed

    private void cotSheetHeightQuiltiingShrinkageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetHeightQuiltiingShrinkageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetHeightQuiltiingShrinkageActionPerformed

    private void cotSheetSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetSubmitButtonActionPerformed
        CotSheetViewModel cCost = new CotSheetViewModel();

        String materialType = (String) cotSheetMaterialTypeCombo.getSelectedItem();
        cCost.setMaterialType(materialType);

        String size = (String) cotSheetSizeCombo.getSelectedItem();
        cCost.setSize(size);

        String paddingType = (String) cotSheetPaddingTypeCombo.getSelectedItem();
        cCost.setPaddingType(paddingType);

        String taffataType = (String) cotSheetTaffataTypeCombo.getSelectedItem();
        cCost.setTaffataType(taffataType);

        try {
            double withQuiltingShrinkage = Double.parseDouble(cotSheetWidthQuiltingShrinkage.getText());
            if (withQuiltingShrinkage < 0 || withQuiltingShrinkage > 20) {
                JOptionPane.showMessageDialog(this, "Width quilting shrinkage should be between 0 and 20 %");
                return;
            }
            cCost.setWidthQuiltyShrinkage(withQuiltingShrinkage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid width quilting shrinkage value");
            return;
        }

        try {
            double otherCost = Double.parseDouble(cotSheetOtherCostVal.getText());
            if (otherCost < 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid value for other costs");
                return;
            }
            cCost.setOtherCost(otherCost);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid value for other costs");
            return;
        }

        try {
            double margin = Double.parseDouble(cotSheetsMarginField.getText());
            if (margin < 0) {
                JOptionPane.showMessageDialog(this, "Profit margin should be a positive value");
                return;
            }
            cCost.setMargin(margin);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid margin value");
            return;
        }

        try {
            double taxRate = Double.parseDouble(cotSheetTaxField.getText());
            if (taxRate < 0) {
                JOptionPane.showMessageDialog(this, "Tax rate should be a positive value");
                return;
            }
            cCost.setTaxRate(taxRate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid tax rate value");
            return;
        }

        try {
            double heightQuiltingShrinkage = Double.parseDouble(cotSheetHeightQuiltiingShrinkage.getText());
            if (heightQuiltingShrinkage < 0 || heightQuiltingShrinkage > 20) {
                JOptionPane.showMessageDialog(this, "Width quilting shrinkage should be between 0 and 20 %");
                return;
            }
            cCost.setHeightQuiltyShrinkage(heightQuiltingShrinkage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid height quilting shrinkage value");
            return;
        }

        try {
            double fabricWastage = Double.parseDouble(cotSheetFabricWastage.getText());
            if (fabricWastage < 0 || fabricWastage > 10) {
                JOptionPane.showMessageDialog(this, "Fabric wastage should be between 0 and 10 %");
                return;
            }
            cCost.setFabricWastage(fabricWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid fabric wastage value");
            return;
        }


        try {
            double taffataWastage = Double.parseDouble(cotSheetTaffateWastage.getText());
            if (taffataWastage < 0 || taffataWastage > 20) {
                JOptionPane.showMessageDialog(this, "Taffata wastage should be between 0 and 20 %");
                return;
            }
            cCost.setTaffataWastage(taffataWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid taffta wastage value");
            return;
        }


        try {
            double paddingWastage = Double.parseDouble(cotSheetPaddingWastage.getText());
            if (paddingWastage < 0 || paddingWastage > 20) {
                JOptionPane.showMessageDialog(this, "Padding wastage should be between 0 and 20 %");
                return;
            }
            cCost.setPaddingWastage(paddingWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid padding wastage value");
            return;
        }

        boolean useCustom = cotSheetUseCustom.isSelected();
        if (useCustom) {
            cCost.setIsCustom(useCustom);
            try {
                Double width = Double.parseDouble(cotSheetCustomWidth.getText());
                if (width <= 0 || width > 120) {
                    JOptionPane.showMessageDialog(this, "Width should be between 0 and 120");
                    return;
                }
                cCost.setCustomWidth(width);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid width value");
                return;
            }

            try {
                Double height = Double.parseDouble(cotSheetCustomHeight.getText());
                if (height <= 0 || height > 120) {
                    JOptionPane.showMessageDialog(this, "Height should be between 0 and 120");
                    return;
                }
                cCost.setCustomHeight(height);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid height value");
                return;
            }

            cCost.setIncludeLable(cotSheetIncludeLable.isSelected());
            cCost.setIncludeTag(cotSheetIncludeTag.isSelected());
            cCost.setIncludePEBag(cotSheetIncludePEBag.isSelected());
        }
        DecimalFormat format = new DecimalFormat();
        format.setMaximumFractionDigits(2);
        format.setMinimumFractionDigits(2);

        CotSheetViewModel cReturn = CotSheetLogic.getCostPerUnit(cCost);
        cotSheetFabricCost.setText(format.format(cReturn.getFabricCost()) + "");
        cotSheetPaddingCost.setText(format.format(cReturn.getPaddingCost()) + "");
        cotSheetTaffataCost.setText(format.format(cReturn.getTaffataCost()) + "");
        cotSheetThreadCost.setText(format.format(cReturn.getThreadCost()) + "");
        cotSheetLableCost.setText(format.format(cReturn.getLableCost()) + "");
        cotSheetTagCost.setText(format.format(cReturn.getTagCost()) + "");
        cotSheetElasticCost.setText(format.format(cReturn.getElasticCost()) + "");
        cotSheetPEBagCost.setText(format.format(cReturn.getPEBagCost()) + "");
        cotSheetTotalMaterialCost.setText(format.format(cReturn.getTotalMaterialCost()) + "");
        cotSheetPOH.setText(format.format(cReturn.getPohCost()) + "");
        cotSheetLabourCost.setText(format.format(cReturn.getLabourCost()) + "");
        cotSheetToatalCost.setText(format.format(cReturn.getTotalCost()) + "");
        cotSheetFabricPaddingCutWidth.setText(format.format(cReturn.getFabricPaddingCuttingWidth()) + "");
        cotSheetFabricPaddingCutHeight.setText(format.format(cReturn.getFabricPaddingCuttingHeight()) + "");
        cotSheetTafffataCutWidth.setText(format.format(cReturn.getTaffataCuttingWidth()) + "");
        cotSheetTaffataCutHeight.setText(format.format(cReturn.getTaffataCuttingWidth()) + "");
        cotSheetSMVValue.setText(format.format(cReturn.getSmvValue()) + "");
        cotSheetNetSellingPrice.setText(format.format(cReturn.getNetSellingPrice()));
        cotSheetTaxes.setText(format.format(cReturn.getTaxes()));
        cotSheetGrossSellingPrice.setText(format.format(cReturn.getGrossSellingPrice()));

        cotSheetCPUPanel.setVisible(true);
    }//GEN-LAST:event_cotSheetSubmitButtonActionPerformed

    private void cotSheetUseCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetUseCustomActionPerformed
        if (cotSheetUseCustom.isSelected()) {
            cotSheetCustomPanel.setVisible(true);
            cotSheetSizeCombo.setVisible(false);
            cotSheetSizeLable.setVisible(false);
        } else {
            cotSheetCustomPanel.setVisible(false);
            cotSheetSizeCombo.setVisible(true);
            cotSheetSizeLable.setVisible(true);
        }
}//GEN-LAST:event_cotSheetUseCustomActionPerformed

    private void cotSheetExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetExportButtonActionPerformed
        //ading the quotation object
        QuationObject qObject = new QuationObject(
                "Cot Sheet",
                "",
                cotSheetMaterialTypeCombo.getSelectedItem() + "",
                cotSheetUseCustom.isSelected() == true ? cotSheetCustomHeight.getText() + "X" + cotSheetCustomWidth.getText() : cotSheetSizeCombo.getSelectedItem() + "",
                1,
                Double.parseDouble(cotSheetGrossSellingPrice.getText().replaceAll(",", "")));

        //adding the costing summary object
        SummaryObject summaryObj = new SummaryObject(
                "Cot Sheet",
                "",
                cotSheetMaterialTypeCombo.getSelectedItem() + "",
                cotSheetPaddingTypeCombo.getSelectedItem() + "",
                cotSheetUseCustom.isSelected() == true ? cotSheetCustomHeight.getText() + "X" + cotSheetCustomWidth.getText() : cotSheetSizeCombo.getSelectedItem() + "",
                1,
                Double.parseDouble(cotSheetToatalCost.getText().replaceAll(",", "")),
                Double.parseDouble(cotSheetsMarginField.getText().replaceAll(",", "")),
                Double.parseDouble(cotSheetTaxField.getText().replaceAll(",", "")));

        //have to add data to this
        ArrayList<Map.Entry<String, String>> prodSpecs = new ArrayList<Map.Entry<String, String>>();
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Fabric Type", cotSheetMaterialTypeCombo.getSelectedItem() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Size", cotSheetUseCustom.isSelected() == true ? cotSheetCustomHeight.getText() + "X" + cotSheetCustomWidth.getText() : cotSheetSizeCombo.getSelectedItem() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Padding Type", cotSheetPaddingTypeCombo.getSelectedItem() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Taffata Type", cotSheetTaffataTypeCombo.getSelectedItem() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Width Quilting Shrinkage", cotSheetWidthQuiltingShrinkage.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Height Quilting Shrinkage", cotSheetHeightQuiltiingShrinkage.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Fabric Wastage", cotSheetFabricWastage.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Taffata Wastage", cotSheetTaffateWastage.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Padding Wastage", cotSheetPaddingWastage.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Include Lable", cotSheetIncludeLable.isSelected() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Include Tag", cotSheetIncludeTag.isSelected() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Include PE Bag", cotSheetIncludePEBag.isSelected() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Margin", cotSheetsMarginField.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Taxes", cotSheetTaxField.getText() + ""));
        prodSpecs.add(new AbstractMap.SimpleEntry<String, String>("Other Costs", cotSheetOtherCostVal.getText() + ""));

        ArrayList<Map.Entry<String, String>> costDescs = new ArrayList<Map.Entry<String, String>>();
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Fabric Cost", cotSheetFabricCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Padding Cost", cotSheetPaddingCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Taffata Cost", cotSheetTaffataCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Thread Cost", cotSheetThreadCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Lable Cost", cotSheetLableCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Tag Cost", cotSheetTagCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Elastic Cost", cotSheetElasticCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("PE Bag Cost", cotSheetPEBagCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Total Material Cost", cotSheetTotalMaterialCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("POH", cotSheetPOH.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Labour Cost", cotSheetLabourCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Total Cost Per Unit", cotSheetToatalCost.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Net Selling Price", cotSheetNetSellingPrice.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Taxes", cotSheetTaxes.getText() + ""));
        costDescs.add(new AbstractMap.SimpleImmutableEntry<String, String>("Gross Selling Price", cotSheetGrossSellingPrice.getText() + ""));

        ArrayList<Map.Entry<String, String>> manuSpecs = new ArrayList<Map.Entry<String, String>>();
        manuSpecs.add(new AbstractMap.SimpleEntry<String, String>("Fabric Padding Cut Width", cotSheetFabricPaddingCutWidth.getText()));
        manuSpecs.add(new AbstractMap.SimpleEntry<String, String>("Fabric Padding Cut Height", cotSheetFabricPaddingCutHeight.getText()));
        manuSpecs.add(new AbstractMap.SimpleEntry<String, String>("Taffata Cut Width", cotSheetTafffataCutWidth.getText()));
        manuSpecs.add(new AbstractMap.SimpleEntry<String, String>("Taffata Cut Height", cotSheetTaffataCutHeight.getText()));
        manuSpecs.add(new AbstractMap.SimpleEntry<String, String>("SMV Value", cotSheetSMVValue.getText()));

        
        try {
            int n = Integer.parseInt(quantity.getText());
            qObject.setQuantity(n);
            summaryObj.setQuantity(n);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity value");
            return;
        }

        
        ItemSummaryObject itemSumObj = new ItemSummaryObject("Cot Sheet", summaryObj, prodSpecs, costDescs, manuSpecs);
        MainWindow.quotation.addQuatationObject(qObject, itemSumObj);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final AddOrderSuccess dialog = new AddOrderSuccess(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
}//GEN-LAST:event_cotSheetExportButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cotSheetCPUPanel;
    private javax.swing.JPanel cotSheetCostingPanel;
    private javax.swing.JTextField cotSheetCustomHeight;
    private javax.swing.JPanel cotSheetCustomPanel;
    private javax.swing.JTextField cotSheetCustomWidth;
    private javax.swing.JLabel cotSheetElasticCost;
    private javax.swing.JButton cotSheetExportButton;
    private javax.swing.JLabel cotSheetFabricCost;
    private javax.swing.JLabel cotSheetFabricPaddingCutHeight;
    private javax.swing.JLabel cotSheetFabricPaddingCutWidth;
    private javax.swing.JTextField cotSheetFabricWastage;
    private javax.swing.JLabel cotSheetGrossSellingPrice;
    private javax.swing.JTextField cotSheetHeightQuiltiingShrinkage;
    private javax.swing.JRadioButton cotSheetIncludeLable;
    private javax.swing.JRadioButton cotSheetIncludePEBag;
    private javax.swing.JRadioButton cotSheetIncludeTag;
    private javax.swing.JLabel cotSheetLableCost;
    private javax.swing.JLabel cotSheetLabourCost;
    private javax.swing.JComboBox cotSheetMaterialTypeCombo;
    private javax.swing.JLabel cotSheetNetSellingPrice;
    private javax.swing.JTextField cotSheetOtherCostVal;
    private javax.swing.JLabel cotSheetPEBagCost;
    private javax.swing.JLabel cotSheetPOH;
    private javax.swing.JLabel cotSheetPaddingCost;
    private javax.swing.JComboBox cotSheetPaddingTypeCombo;
    private javax.swing.JTextField cotSheetPaddingWastage;
    private javax.swing.JLabel cotSheetSMVValue;
    private javax.swing.JComboBox cotSheetSizeCombo;
    private javax.swing.JLabel cotSheetSizeLable;
    private javax.swing.JButton cotSheetSubmitButton;
    private javax.swing.JLabel cotSheetTaffataCost;
    private javax.swing.JLabel cotSheetTaffataCutHeight;
    private javax.swing.JComboBox cotSheetTaffataTypeCombo;
    private javax.swing.JTextField cotSheetTaffateWastage;
    private javax.swing.JLabel cotSheetTafffataCutWidth;
    private javax.swing.JLabel cotSheetTagCost;
    private javax.swing.JTextField cotSheetTaxField;
    private javax.swing.JLabel cotSheetTaxes;
    private javax.swing.JLabel cotSheetThreadCost;
    private javax.swing.JLabel cotSheetToatalCost;
    private javax.swing.JLabel cotSheetTotalMaterialCost;
    private javax.swing.JRadioButton cotSheetUseCustom;
    private javax.swing.JTextField cotSheetWidthQuiltingShrinkage;
    private javax.swing.JTextField cotSheetsMarginField;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new CotSheetCostingPanel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
