/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CotSheetCostingPanel.java
 *
 * Created on Apr 25, 2013, 3:17:08 AM
 */

package view;

import celcius.Config;
import java.awt.EventQueue;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.CotSheetLogic;
import viewmodels.CotSheetViewModel;

/**
 *
 * @author naka
 */
public class CotSheetCostingPanel extends javax.swing.JPanel {

    /** Creates new form CotSheetCostingPanel */
    public CotSheetCostingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cotSheetCostingPanel = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        cotSheetMaterialTypeCombo = new javax.swing.JComboBox();
        cotSheetSizeCombo = new javax.swing.JComboBox();
        cotSheetFabricWastage = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        cotSheetSizeLable = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        cotSheetCustomPanel = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        cotSheetCustomWidth = new javax.swing.JTextField();
        cotSheetCustomHeight = new javax.swing.JTextField();
        cotSheetIncludeLable = new javax.swing.JRadioButton();
        cotSheetIncludeTag = new javax.swing.JRadioButton();
        cotSheetIncludePEBag = new javax.swing.JRadioButton();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        cotSheetTaffateWastage = new javax.swing.JTextField();
        cotSheetPaddingWastage = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        cotSheetPaddingTypeCombo = new javax.swing.JComboBox();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        cotSheetWidthQuiltingShrinkage = new javax.swing.JTextField();
        cotSheetHeightQuiltiingShrinkage = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        cotSheetTaffataTypeCombo = new javax.swing.JComboBox();
        cotSheetSubmitButton = new javax.swing.JButton();
        cotSheetUseCustom = new javax.swing.JRadioButton();
        cotSheetNewCosting = new javax.swing.JButton();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        cotSheetTaxField = new javax.swing.JTextField();
        jLabel307 = new javax.swing.JLabel();
        jLabel308 = new javax.swing.JLabel();
        cotSheetsMarginField = new javax.swing.JTextField();
        cotSheetCPUPanel = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        cotSheetLabourCost = new javax.swing.JLabel();
        cotSheetPEBagCost = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        cotSheetTotalMaterialCost = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        cotSheetFabricCost = new javax.swing.JLabel();
        cotSheetThreadCost = new javax.swing.JLabel();
        cotSheetLableCost = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        cotSheetPaddingCost = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        cotSheetTaffataCost = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        cotSheetToatalCost = new javax.swing.JLabel();
        cotSheetElasticCost = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        cotSheetTagCost = new javax.swing.JLabel();
        cotSheetPOH = new javax.swing.JLabel();
        jLabel337 = new javax.swing.JLabel();
        jLabel338 = new javax.swing.JLabel();
        jLabel339 = new javax.swing.JLabel();
        cotSheetNetSellingPrice = new javax.swing.JLabel();
        cotSheetGrossSellingPrice = new javax.swing.JLabel();
        cotSheetTaxes = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        cotSheetTafffataCutWidth = new javax.swing.JLabel();
        cotSheetSMVValue = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        cotSheetFabricPaddingCutWidth = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        cotSheetTaffataCutHeight = new javax.swing.JLabel();
        cotSheetFabricPaddingCutHeight = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();

        cotSheetCostingPanel.setBackground(new java.awt.Color(204, 204, 204));
        cotSheetCostingPanel.setMinimumSize(new java.awt.Dimension(500, 600));
        cotSheetCostingPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel119.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel119.setText("Cot Sheets Costing");

        jLabel121.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel121.setText("Select Fabric Type:");

        cotSheetMaterialTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetMaterialTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getMaterialTypes()));

        cotSheetSizeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getCotSheetizes()));
        cotSheetSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetSizeComboActionPerformed(evt);
            }
        });

        cotSheetFabricWastage.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetFabricWastage.setText("3");
        cotSheetFabricWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetFabricWastageActionPerformed(evt);
            }
        });

        jLabel122.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel122.setText("%");

        cotSheetSizeLable.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetSizeLable.setText("Select Size:");

        jLabel124.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel124.setText("Fabric Wastage:");

        jLabel125.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel125.setText("Width (inches) :");

        jLabel126.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel126.setText("Height (inches):");

        cotSheetCustomWidth.setFont(new java.awt.Font("Times New Roman", 0, 16));

        cotSheetCustomHeight.setFont(new java.awt.Font("Times New Roman", 0, 16));

        cotSheetIncludeLable.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetIncludeLable.setText("Include Lable");

        cotSheetIncludeTag.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetIncludeTag.setText("Include Tag");

        cotSheetIncludePEBag.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetIncludePEBag.setText("Include PE Bag");

        javax.swing.GroupLayout cotSheetCustomPanelLayout = new javax.swing.GroupLayout(cotSheetCustomPanel);
        cotSheetCustomPanel.setLayout(cotSheetCustomPanelLayout);
        cotSheetCustomPanelLayout.setHorizontalGroup(
            cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotSheetIncludeTag)
                    .addComponent(cotSheetIncludePEBag)
                    .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                        .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel126)
                            .addComponent(jLabel125))
                        .addGap(122, 122, 122)
                        .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                                .addComponent(cotSheetCustomWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(cotSheetCustomHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cotSheetIncludeLable))
                .addGap(93, 93, 93))
        );
        cotSheetCustomPanelLayout.setVerticalGroup(
            cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCustomPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel125)
                    .addComponent(cotSheetCustomWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel126)
                    .addComponent(cotSheetCustomHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetIncludeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetIncludeTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetIncludePEBag)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel127.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel127.setText("Taffata Wastage:");

        jLabel128.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel128.setText("Padding Wastage:");

        cotSheetTaffateWastage.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTaffateWastage.setText("3");
        cotSheetTaffateWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetTaffateWastageActionPerformed(evt);
            }
        });

        cotSheetPaddingWastage.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetPaddingWastage.setText("3");
        cotSheetPaddingWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetPaddingWastageActionPerformed(evt);
            }
        });

        jLabel129.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel129.setText("%");

        jLabel130.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel130.setText("%");

        jLabel131.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel131.setText("Select Padding Type:");

        cotSheetPaddingTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetPaddingTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getPaddingTypes()));

        jLabel132.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel132.setText("Width Quilting Shrinkage:");

        jLabel133.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel133.setText("Height Quilting Shrinkage:");

        cotSheetWidthQuiltingShrinkage.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetWidthQuiltingShrinkage.setText("8");
        cotSheetWidthQuiltingShrinkage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetWidthQuiltingShrinkageActionPerformed(evt);
            }
        });

        cotSheetHeightQuiltiingShrinkage.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetHeightQuiltiingShrinkage.setText("3");
        cotSheetHeightQuiltiingShrinkage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetHeightQuiltiingShrinkageActionPerformed(evt);
            }
        });

        jLabel134.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel134.setText("%");

        jLabel135.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel135.setText("%");

        jLabel136.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel136.setText("Select Taffata Type:");

        cotSheetTaffataTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTaffataTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CotSheetLogic.getTaffataTypes()));

        cotSheetSubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetSubmitButton.setText("Find Cost Per Unit");
        cotSheetSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetSubmitButtonActionPerformed(evt);
            }
        });

        cotSheetUseCustom.setBackground(new java.awt.Color(204, 204, 204));
        cotSheetUseCustom.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetUseCustom.setText("Use Custom Sizes");
        cotSheetUseCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetUseCustomActionPerformed(evt);
            }
        });

        cotSheetNewCosting.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetNewCosting.setText("New Costing");
        cotSheetNewCosting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotSheetNewCostingActionPerformed(evt);
            }
        });

        jLabel305.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel305.setText("Margin:");

        jLabel306.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel306.setText("Taxes:");

        cotSheetTaxField.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTaxField.setText(Config.taxesRate);

        jLabel307.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel307.setText("%");

        jLabel308.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel308.setText("%");

        cotSheetsMarginField.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetsMarginField.setText(Config.profitMargin);

        javax.swing.GroupLayout cotSheetCostingPanelLayout = new javax.swing.GroupLayout(cotSheetCostingPanel);
        cotSheetCostingPanel.setLayout(cotSheetCostingPanelLayout);
        cotSheetCostingPanelLayout.setHorizontalGroup(
            cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel119)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel306)
                            .addComponent(jLabel305))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addComponent(cotSheetTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel307))
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addComponent(cotSheetsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel308)))
                        .addGap(153, 153, 153))
                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cotSheetCustomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel128)
                                    .addComponent(jLabel127)
                                    .addComponent(jLabel124)
                                    .addComponent(jLabel133)
                                    .addComponent(jLabel132)
                                    .addComponent(jLabel136)
                                    .addComponent(jLabel131)
                                    .addComponent(cotSheetSizeLable)
                                    .addComponent(jLabel121)
                                    .addComponent(cotSheetUseCustom))
                                .addGap(70, 70, 70)
                                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cotSheetPaddingTypeCombo, 0, 203, Short.MAX_VALUE)
                                    .addComponent(cotSheetSizeCombo, 0, 203, Short.MAX_VALUE)
                                    .addComponent(cotSheetMaterialTypeCombo, 0, 203, Short.MAX_VALUE)
                                    .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                        .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetPaddingWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel130))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetTaffateWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel129))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetHeightQuiltiingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel135))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetWidthQuiltingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel134))
                                            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                                                .addComponent(cotSheetFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel122)))
                                        .addGap(158, 158, 158))
                                    .addComponent(cotSheetTaffataTypeCombo, 0, 203, Short.MAX_VALUE))))
                        .addGap(47, 47, 47))))
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cotSheetSubmitButton)
                    .addComponent(cotSheetNewCosting))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        cotSheetCostingPanelLayout.setVerticalGroup(
            cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCostingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel119)
                .addGap(18, 18, 18)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetMaterialTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cotSheetSizeLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetPaddingTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel131))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotSheetTaffataTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136))
                .addGap(11, 11, 11)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel134)
                    .addComponent(cotSheetWidthQuiltingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cotSheetHeightQuiltiingShrinkage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135)
                    .addComponent(jLabel133))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel122)
                    .addComponent(cotSheetFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel124))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel129)
                    .addComponent(cotSheetTaffateWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel127))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel128)
                    .addComponent(cotSheetPaddingWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel130))
                .addGap(23, 23, 23)
                .addComponent(cotSheetUseCustom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetCustomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel305)
                    .addComponent(cotSheetsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel308))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cotSheetCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel307)
                    .addComponent(cotSheetTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel306))
                .addGap(18, 18, 18)
                .addComponent(cotSheetSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cotSheetNewCosting)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        cotSheetCustomPanel.setVisible(false);
        cotSheetNewCosting.setVisible(false);

        jPanel31.setBackground(new java.awt.Color(204, 204, 204));

        jLabel143.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel143.setText("Labour Cost:");

        cotSheetLabourCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetLabourCost.setText("0.00");

        cotSheetPEBagCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetPEBagCost.setText("0.00");

        jLabel139.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel139.setText("Lable Cost:");

        cotSheetTotalMaterialCost.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cotSheetTotalMaterialCost.setText("0.00");

        jLabel137.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel137.setText("Fabric Cost:");

        cotSheetFabricCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetFabricCost.setText("0.00");

        cotSheetThreadCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetThreadCost.setText("0.00");

        cotSheetLableCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetLableCost.setText("0.00");

        jLabel140.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel140.setText("Tag Cost:");

        jLabel151.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel151.setText("Total Material Cost");

        jLabel150.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel150.setText("Elastic Cost: ");

        cotSheetPaddingCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetPaddingCost.setText("0.00");

        jLabel141.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel141.setText("PE Bag Cost:");

        cotSheetTaffataCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTaffataCost.setText("0.00");

        jLabel144.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel144.setText("Toatal Cost Per Unit:");

        jLabel142.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel142.setText("POH:");

        jLabel153.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel153.setText("Padding Cost:");

        jLabel154.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel154.setText("Taffata Cost:");

        jLabel145.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel145.setText("Cost Per Unit");

        cotSheetToatalCost.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cotSheetToatalCost.setText("0.00");

        cotSheetElasticCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetElasticCost.setText("0.00");

        jLabel138.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel138.setText("Thread Cost:");

        cotSheetTagCost.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTagCost.setText("0.00");

        cotSheetPOH.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetPOH.setText("0.00");

        jLabel337.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel337.setText("Net Selling Price:");

        jLabel338.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel338.setText("Taxes:");

        jLabel339.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel339.setText("Gross Selling Price:");

        cotSheetNetSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cotSheetNetSellingPrice.setText("0.00");

        cotSheetGrossSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cotSheetGrossSellingPrice.setText("0.00");

        cotSheetTaxes.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cotSheetTaxes.setText("0.00");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel145))
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel339)
                            .addComponent(jLabel338)
                            .addComponent(jLabel337)
                            .addComponent(jLabel144)
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel154)
                                    .addComponent(jLabel140)
                                    .addComponent(jLabel153)
                                    .addComponent(jLabel139)
                                    .addComponent(jLabel151)
                                    .addComponent(jLabel150)
                                    .addComponent(jLabel141)
                                    .addComponent(jLabel138)
                                    .addComponent(jLabel137)
                                    .addComponent(jLabel143)
                                    .addComponent(jLabel142))
                                .addGap(229, 229, 229)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cotSheetTotalMaterialCost)
                                    .addComponent(cotSheetElasticCost)
                                    .addComponent(cotSheetTagCost)
                                    .addComponent(cotSheetLableCost)
                                    .addComponent(cotSheetThreadCost)
                                    .addComponent(cotSheetFabricCost)
                                    .addComponent(cotSheetTaffataCost)
                                    .addComponent(cotSheetPaddingCost)
                                    .addComponent(cotSheetPEBagCost)
                                    .addComponent(cotSheetToatalCost)
                                    .addComponent(cotSheetLabourCost)
                                    .addComponent(cotSheetPOH)
                                    .addComponent(cotSheetNetSellingPrice)
                                    .addComponent(cotSheetGrossSellingPrice)
                                    .addComponent(cotSheetTaxes))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addComponent(cotSheetFabricCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetPaddingCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetTaffataCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetThreadCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetLableCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetTagCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetElasticCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cotSheetPEBagCost)
                                .addGap(18, 18, 18)
                                .addComponent(cotSheetTotalMaterialCost)
                                .addGap(18, 18, 18)
                                .addComponent(cotSheetPOH))
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addComponent(jLabel137)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel153)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel154)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel138)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel139)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel140)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel150)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel141)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel151)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel142))))
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel143)
                            .addComponent(cotSheetLabourCost))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel144)
                            .addComponent(cotSheetToatalCost))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel337)
                    .addComponent(cotSheetNetSellingPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel338)
                    .addComponent(cotSheetTaxes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel339)
                    .addComponent(cotSheetGrossSellingPrice))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel32.setBackground(new java.awt.Color(204, 204, 204));

        cotSheetTafffataCutWidth.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTafffataCutWidth.setText("0.00");

        cotSheetSMVValue.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetSMVValue.setText("0.00");

        jLabel148.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel148.setText("SMV Value:");

        jLabel146.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel146.setText("Fabric/Padding Cutting Width:");

        jLabel156.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel156.setText("Taffata Cutting Height:");

        cotSheetFabricPaddingCutWidth.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetFabricPaddingCutWidth.setText("0.00");

        jLabel149.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel149.setText("Production Parameters");

        jLabel155.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel155.setText("Taffata Cutting Width:");

        cotSheetTaffataCutHeight.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetTaffataCutHeight.setText("0.00");

        cotSheetFabricPaddingCutHeight.setFont(new java.awt.Font("Times New Roman", 0, 16));
        cotSheetFabricPaddingCutHeight.setText("0.00");

        jLabel147.setFont(new java.awt.Font("Times New Roman", 0, 16));
        jLabel147.setText("Fabric/Padding Cutting Height:");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel156)
                    .addComponent(jLabel147)
                    .addComponent(jLabel146)
                    .addComponent(jLabel155)
                    .addComponent(jLabel148))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotSheetTafffataCutWidth, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetTaffataCutHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetSMVValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetFabricPaddingCutHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cotSheetFabricPaddingCutWidth, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel149)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel149, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(cotSheetFabricPaddingCutWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetFabricPaddingCutHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetTafffataCutWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetTaffataCutHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cotSheetSMVValue))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel146)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel147)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel155)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel156)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel148)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cotSheetCPUPanelLayout = new javax.swing.GroupLayout(cotSheetCPUPanel);
        cotSheetCPUPanel.setLayout(cotSheetCPUPanelLayout);
        cotSheetCPUPanelLayout.setHorizontalGroup(
            cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cotSheetCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        cotSheetCPUPanelLayout.setVerticalGroup(
            cotSheetCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cotSheetCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cotSheetCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cotSheetCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cotSheetCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cotSheetCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cotSheetCPUPanel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void cotSheetSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetSizeComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetSizeComboActionPerformed

    private void cotSheetFabricWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetFabricWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetFabricWastageActionPerformed

    private void cotSheetTaffateWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetTaffateWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetTaffateWastageActionPerformed

    private void cotSheetPaddingWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetPaddingWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetPaddingWastageActionPerformed

    private void cotSheetWidthQuiltingShrinkageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetWidthQuiltingShrinkageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetWidthQuiltingShrinkageActionPerformed

    private void cotSheetHeightQuiltiingShrinkageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetHeightQuiltiingShrinkageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cotSheetHeightQuiltiingShrinkageActionPerformed

    private void cotSheetSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetSubmitButtonActionPerformed
        CotSheetViewModel cCost = new CotSheetViewModel();

        String materialType = (String) cotSheetMaterialTypeCombo.getSelectedItem();
        cCost.setMaterialType(materialType);

        String size = (String) cotSheetSizeCombo.getSelectedItem();
        cCost.setSize(size);

        String paddingType = (String) cotSheetPaddingTypeCombo.getSelectedItem();
        cCost.setPaddingType(paddingType);

        String taffataType = (String) cotSheetTaffataTypeCombo.getSelectedItem();
        cCost.setTaffataType(taffataType);

        try {
            double withQuiltingShrinkage = Double.parseDouble(cotSheetWidthQuiltingShrinkage.getText());
            if (withQuiltingShrinkage < 0 || withQuiltingShrinkage > 20) {
                JOptionPane.showMessageDialog(this, "Width quilting shrinkage should be between 0 and 20 %");
                return;
            }
            cCost.setWidthQuiltyShrinkage(withQuiltingShrinkage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid width quilting shrinkage value");
            return;
        }

        try {
            double heightQuiltingShrinkage = Double.parseDouble(cotSheetHeightQuiltiingShrinkage.getText());
            if (heightQuiltingShrinkage < 0 || heightQuiltingShrinkage > 20) {
                JOptionPane.showMessageDialog(this, "Width quilting shrinkage should be between 0 and 20 %");
                return;
            }
            cCost.setHeightQuiltyShrinkage(heightQuiltingShrinkage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid height quilting shrinkage value");
            return;
        }

        try {
            double fabricWastage = Double.parseDouble(cotSheetFabricWastage.getText());
            if (fabricWastage < 0 || fabricWastage > 10) {
                JOptionPane.showMessageDialog(this, "Fabric wastage should be between 0 and 10 %");
                return;
            }
            cCost.setFabricWastage(fabricWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid fabric wastage value");
            return;
        }


        try {
            double taffataWastage = Double.parseDouble(cotSheetTaffateWastage.getText());
            if (taffataWastage < 0 || taffataWastage > 20) {
                JOptionPane.showMessageDialog(this, "Taffata wastage should be between 0 and 20 %");
                return;
            }
            cCost.setTaffataWastage(taffataWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid taffta wastage value");
            return;
        }


        try {
            double paddingWastage = Double.parseDouble(cotSheetPaddingWastage.getText());
            if (paddingWastage < 0 || paddingWastage > 20) {
                JOptionPane.showMessageDialog(this, "Padding wastage should be between 0 and 20 %");
                return;
            }
            cCost.setPaddingWastage(paddingWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid padding wastage value");
            return;
        }

        boolean useCustom = cotSheetUseCustom.isSelected();
        if (useCustom) {
            cCost.setIsCustom(useCustom);
            try {
                Integer width = Integer.parseInt(cotSheetCustomWidth.getText());
                if (width <= 0 || width > 120) {
                    JOptionPane.showMessageDialog(this, "Width should be between 0 and 120");
                    return;
                }
                cCost.setCustomWidth(width);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid width value");
                return;
            }

            try {
                Integer height = Integer.parseInt(cotSheetCustomHeight.getText());
                if (height <= 0 || height > 120) {
                    JOptionPane.showMessageDialog(this, "Height should be between 0 and 120");
                    return;
                }
                cCost.setCustomHeight(height);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid height value");
                return;
            }

            cCost.setIncludeLable(cotSheetIncludeLable.isSelected());
            cCost.setIncludeTag(cotSheetIncludeTag.isSelected());
            cCost.setIncludePEBag(cotSheetIncludePEBag.isSelected());
        }
        DecimalFormat format = new DecimalFormat();
        format.setMaximumFractionDigits(2);
        format.setMinimumFractionDigits(2);

        CotSheetViewModel cReturn = CotSheetLogic.getCostPerUnit(cCost);
        cotSheetFabricCost.setText(format.format(cReturn.getFabricCost()) + "");
        cotSheetPaddingCost.setText(format.format(cReturn.getPaddingCost()) + "");
        cotSheetTaffataCost.setText(format.format(cReturn.getTaffataCost()) + "");
        cotSheetThreadCost.setText(format.format(cReturn.getThreadCost()) + "");
        cotSheetLableCost.setText(format.format(cReturn.getLableCost()) + "");
        cotSheetTagCost.setText(format.format(cReturn.getTagCost()) + "");
        cotSheetElasticCost.setText(format.format(cReturn.getElasticCost()) + "");
        cotSheetPEBagCost.setText(format.format(cReturn.getPEBagCost()) + "");
        cotSheetTotalMaterialCost.setText(format.format(cReturn.getTotalMaterialCost()) + "");
        cotSheetPOH.setText(format.format(cReturn.getPohCost()) + "");
        cotSheetLabourCost.setText(format.format(cReturn.getLabourCost()) + "");
        cotSheetToatalCost.setText(format.format(cReturn.getTotalCost()) + "");
        cotSheetFabricPaddingCutWidth.setText(format.format(cReturn.getFabricPaddingCuttingWidth()) + "");
        cotSheetFabricPaddingCutHeight.setText(format.format(cReturn.getFabricPaddingCuttingHeight()) + "");
        cotSheetTafffataCutWidth.setText(format.format(cReturn.getTaffataCuttingWidth()) + "");
        cotSheetTaffataCutHeight.setText(format.format(cReturn.getTaffataCuttingWidth()) + "");
        cotSheetSMVValue.setText(format.format(cReturn.getSmvValue()) + "");

        cotSheetCPUPanel.setVisible(true);
        cotSheetSubmitButton.setVisible(false);
        cotSheetNewCosting.setVisible(true);

        //disabling input fields
        cotSheetMaterialTypeCombo.setEnabled(false);
        cotSheetSizeCombo.setEnabled(false);
        cotSheetPaddingTypeCombo.setEnabled(false);
        cotSheetTaffataTypeCombo.setEnabled(false);
        cotSheetWidthQuiltingShrinkage.setEnabled(false);
        cotSheetHeightQuiltiingShrinkage.setEnabled(false);
        cotSheetFabricWastage.setEnabled(false);
        cotSheetTaffateWastage.setEnabled(false);
        cotSheetPaddingWastage.setEnabled(false);

        cotSheetUseCustom.setEnabled(false);
        cotSheetCustomHeight.setEnabled(false);
        cotSheetCustomWidth.setEnabled(false);

        cotSheetIncludeLable.setEnabled(false);
        cotSheetIncludePEBag.setEnabled(false);
        cotSheetIncludeTag.setEnabled(false);
    }//GEN-LAST:event_cotSheetSubmitButtonActionPerformed

    private void cotSheetUseCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetUseCustomActionPerformed
        if (cotSheetUseCustom.isSelected()) {
            cotSheetCustomPanel.setVisible(true);
            cotSheetSizeCombo.setVisible(false);
            cotSheetSizeLable.setVisible(false);
        } else {
            cotSheetCustomPanel.setVisible(false);
            cotSheetSizeCombo.setVisible(true);
            cotSheetSizeLable.setVisible(true);
        }
}//GEN-LAST:event_cotSheetUseCustomActionPerformed

    private void cotSheetNewCostingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotSheetNewCostingActionPerformed
        cotSheetCPUPanel.setVisible(false);
        cotSheetSubmitButton.setVisible(true);
        cotSheetNewCosting.setVisible(false);

        cotSheetMaterialTypeCombo.setModel(new DefaultComboBoxModel(
                CotSheetLogic.getMaterialTypes()));
        cotSheetSizeCombo.setModel(new DefaultComboBoxModel(
                CotSheetLogic.getCotSheetizes()));
        cotSheetPaddingTypeCombo.setModel(
                new DefaultComboBoxModel(CotSheetLogic.getPaddingTypes()));
        cotSheetTaffataTypeCombo.setModel(
                new DefaultComboBoxModel(CotSheetLogic.getTaffataTypes()));
        cotSheetWidthQuiltingShrinkage.setText("8");
        cotSheetHeightQuiltiingShrinkage.setText("3");
        cotSheetFabricWastage.setText("3");
        cotSheetTaffateWastage.setText("3");
        cotSheetPaddingWastage.setText("3");

        cotSheetUseCustom.setSelected(false);
        cotSheetCustomPanel.setVisible(false);
        cotSheetCustomHeight.setText("");
        cotSheetCustomWidth.setText("");

        cotSheetIncludeLable.setSelected(false);
        cotSheetIncludePEBag.setSelected(false);
        cotSheetIncludeTag.setSelected(false);

        cotSheetMaterialTypeCombo.setEnabled(true);
        cotSheetSizeCombo.setEnabled(true);
        cotSheetPaddingTypeCombo.setEnabled(true);
        cotSheetTaffataTypeCombo.setEnabled(true);
        cotSheetWidthQuiltingShrinkage.setEnabled(true);
        cotSheetHeightQuiltiingShrinkage.setEnabled(true);
        cotSheetFabricWastage.setEnabled(true);
        cotSheetTaffateWastage.setEnabled(true);
        cotSheetPaddingWastage.setEnabled(true);

        cotSheetUseCustom.setEnabled(true);
        cotSheetCustomHeight.setEnabled(true);
        cotSheetCustomWidth.setEnabled(true);

        cotSheetIncludeLable.setEnabled(true);
        cotSheetIncludePEBag.setEnabled(true);
        cotSheetIncludeTag.setEnabled(true);
}//GEN-LAST:event_cotSheetNewCostingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cotSheetCPUPanel;
    private javax.swing.JPanel cotSheetCostingPanel;
    private javax.swing.JTextField cotSheetCustomHeight;
    private javax.swing.JPanel cotSheetCustomPanel;
    private javax.swing.JTextField cotSheetCustomWidth;
    private javax.swing.JLabel cotSheetElasticCost;
    private javax.swing.JLabel cotSheetFabricCost;
    private javax.swing.JLabel cotSheetFabricPaddingCutHeight;
    private javax.swing.JLabel cotSheetFabricPaddingCutWidth;
    private javax.swing.JTextField cotSheetFabricWastage;
    private javax.swing.JLabel cotSheetGrossSellingPrice;
    private javax.swing.JTextField cotSheetHeightQuiltiingShrinkage;
    private javax.swing.JRadioButton cotSheetIncludeLable;
    private javax.swing.JRadioButton cotSheetIncludePEBag;
    private javax.swing.JRadioButton cotSheetIncludeTag;
    private javax.swing.JLabel cotSheetLableCost;
    private javax.swing.JLabel cotSheetLabourCost;
    private javax.swing.JComboBox cotSheetMaterialTypeCombo;
    private javax.swing.JLabel cotSheetNetSellingPrice;
    private javax.swing.JButton cotSheetNewCosting;
    private javax.swing.JLabel cotSheetPEBagCost;
    private javax.swing.JLabel cotSheetPOH;
    private javax.swing.JLabel cotSheetPaddingCost;
    private javax.swing.JComboBox cotSheetPaddingTypeCombo;
    private javax.swing.JTextField cotSheetPaddingWastage;
    private javax.swing.JLabel cotSheetSMVValue;
    private javax.swing.JComboBox cotSheetSizeCombo;
    private javax.swing.JLabel cotSheetSizeLable;
    private javax.swing.JButton cotSheetSubmitButton;
    private javax.swing.JLabel cotSheetTaffataCost;
    private javax.swing.JLabel cotSheetTaffataCutHeight;
    private javax.swing.JComboBox cotSheetTaffataTypeCombo;
    private javax.swing.JTextField cotSheetTaffateWastage;
    private javax.swing.JLabel cotSheetTafffataCutWidth;
    private javax.swing.JLabel cotSheetTagCost;
    private javax.swing.JTextField cotSheetTaxField;
    private javax.swing.JLabel cotSheetTaxes;
    private javax.swing.JLabel cotSheetThreadCost;
    private javax.swing.JLabel cotSheetToatalCost;
    private javax.swing.JLabel cotSheetTotalMaterialCost;
    private javax.swing.JRadioButton cotSheetUseCustom;
    private javax.swing.JTextField cotSheetWidthQuiltingShrinkage;
    private javax.swing.JTextField cotSheetsMarginField;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new CotSheetCostingPanel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

}
