package view;

import celcius.Config;
import export.Export;
import export.ExportModel;
import java.awt.EventQueue;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.CushionLogic;
import logic.PillowLogic;
import viewmodels.CushionsViewModel;

/**
 *
 * @author naka
 */
public class CushionsCostingPanel extends javax.swing.JPanel {

    private ExportModel model;

    /**
     * Creates new form CushionsCostingPanel
     */
    public CushionsCostingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cushionsCostingPanel = new javax.swing.JPanel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        cushionsRangeCombo = new javax.swing.JComboBox();
        cushionsFabricWastage = new javax.swing.JTextField();
        jLabel260 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        cushionsCustomPanel = new javax.swing.JPanel();
        jLabel263 = new javax.swing.JLabel();
        cushionsCustomWidthHeight = new javax.swing.JTextField();
        cushionsIncludeLable = new javax.swing.JRadioButton();
        cushionsIncludeTag = new javax.swing.JRadioButton();
        cushionsIncludePEBag = new javax.swing.JRadioButton();
        jLabel264 = new javax.swing.JLabel();
        cushionsCustomFiberWeight = new javax.swing.JTextField();
        jLabel265 = new javax.swing.JLabel();
        cushionsFabricTypeCombo = new javax.swing.JComboBox();
        cushionsSizeLable = new javax.swing.JLabel();
        cushionsSizeCombo = new javax.swing.JComboBox();
        cushionsSubmitButton = new javax.swing.JButton();
        cushionsUseCustom = new javax.swing.JRadioButton();
        cushionsNewCostingButton = new javax.swing.JButton();
        cushionsCustomFiberButton = new javax.swing.JRadioButton();
        cushionsFiberTypeCombo = new javax.swing.JComboBox();
        jLabel267 = new javax.swing.JLabel();
        jLabel268 = new javax.swing.JLabel();
        cushionsFiberWastage = new javax.swing.JTextField();
        jLabel269 = new javax.swing.JLabel();
        jLabel317 = new javax.swing.JLabel();
        jLabel318 = new javax.swing.JLabel();
        cushionsTaxField = new javax.swing.JTextField();
        jLabel319 = new javax.swing.JLabel();
        jLabel320 = new javax.swing.JLabel();
        cushionsMarginField = new javax.swing.JTextField();
        jLabel321 = new javax.swing.JLabel();
        cushionsOtherCostVal = new javax.swing.JTextField();
        cushionsCPUPanel = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        cushionsFiberWeight = new javax.swing.JLabel();
        cushionsSMVValue = new javax.swing.JLabel();
        cushionsFabricCutWidthHeight = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel244 = new javax.swing.JLabel();
        jLabel245 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        cushionsLabourCost = new javax.swing.JLabel();
        cushionsFiberCost = new javax.swing.JLabel();
        cushionsThreadCost = new javax.swing.JLabel();
        cushionsTagCost = new javax.swing.JLabel();
        cushionsLableCost = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jLabel254 = new javax.swing.JLabel();
        cushionsPOH = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        jLabel256 = new javax.swing.JLabel();
        cushionsPEBagCost = new javax.swing.JLabel();
        cushionsTotalMaterialCost = new javax.swing.JLabel();
        cushionsFabricCost = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        cushionsToatalCost = new javax.swing.JLabel();
        jLabel346 = new javax.swing.JLabel();
        jLabel347 = new javax.swing.JLabel();
        jLabel348 = new javax.swing.JLabel();
        cushionsNetSellingPrice = new javax.swing.JLabel();
        cushionsTaxes = new javax.swing.JLabel();
        cushionsGrossSellingPrice = new javax.swing.JLabel();
        cushionsExportButton = new javax.swing.JButton();

        cushionsCostingPanel.setPreferredSize(new java.awt.Dimension(556, 600));

        jLabel258.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel258.setText("Cushions Costing");

        jLabel259.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel259.setText("Select Product Range:");

        cushionsRangeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsRangeCombo.setModel(new javax.swing.DefaultComboBoxModel(CushionLogic.getProductRanges()));
        cushionsRangeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsRangeComboActionPerformed(evt);
            }
        });

        cushionsFabricWastage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFabricWastage.setText("3");
        cushionsFabricWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsFabricWastageActionPerformed(evt);
            }
        });

        jLabel260.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel260.setText("%");

        jLabel262.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel262.setText("Fabric Wastage:");

        jLabel263.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel263.setText("Width & Height (inches) :");

        cushionsCustomWidthHeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        cushionsIncludeLable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsIncludeLable.setText("Include Lable");

        cushionsIncludeTag.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsIncludeTag.setText("Include Tag");

        cushionsIncludePEBag.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsIncludePEBag.setText("Include PE Bag");

        jLabel264.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel264.setText("Fiber weight(kg):");

        cushionsCustomFiberWeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsCustomFiberWeight.setText("0.0");

        javax.swing.GroupLayout cushionsCustomPanelLayout = new javax.swing.GroupLayout(cushionsCustomPanel);
        cushionsCustomPanel.setLayout(cushionsCustomPanelLayout);
        cushionsCustomPanelLayout.setHorizontalGroup(
            cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCustomPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cushionsIncludePEBag)
                    .addComponent(cushionsIncludeLable)
                    .addComponent(cushionsIncludeTag)
                    .addGroup(cushionsCustomPanelLayout.createSequentialGroup()
                        .addGroup(cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel263)
                            .addComponent(jLabel264))
                        .addGap(41, 41, 41)
                        .addGroup(cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cushionsCustomFiberWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cushionsCustomWidthHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        cushionsCustomPanelLayout.setVerticalGroup(
            cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCustomPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel263)
                    .addComponent(cushionsCustomWidthHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cushionsCustomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel264)
                    .addComponent(cushionsCustomFiberWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cushionsIncludeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cushionsIncludeTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cushionsIncludePEBag)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel265.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel265.setText("Select Fabric Type:");

        cushionsFabricTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFabricTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(CushionLogic.getMaterialTypes((String)cushionsRangeCombo.getSelectedItem())));
        cushionsFabricTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsFabricTypeComboActionPerformed(evt);
            }
        });

        cushionsSizeLable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsSizeLable.setText("Select Size:");

        cushionsSizeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(CushionLogic.getCushionSizes((String)cushionsRangeCombo.getSelectedItem())));

        cushionsSubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsSubmitButton.setText("Find Cost Per Unit");
        cushionsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsSubmitButtonActionPerformed(evt);
            }
        });

        cushionsUseCustom.setBackground(new java.awt.Color(204, 204, 204));
        cushionsUseCustom.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsUseCustom.setText("Use Custom Sizes");
        cushionsUseCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsUseCustomActionPerformed(evt);
            }
        });

        cushionsNewCostingButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsNewCostingButton.setText("New Costing");
        cushionsNewCostingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsNewCostingButtonActionPerformed(evt);
            }
        });

        cushionsCustomFiberButton.setBackground(new java.awt.Color(204, 204, 204));
        cushionsCustomFiberButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsCustomFiberButton.setText("Custom Fiber Selection");
        cushionsCustomFiberButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cushionsCustomFiberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsCustomFiberButtonActionPerformed(evt);
            }
        });

        cushionsFiberTypeCombo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFiberTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getFiberTypes((String)cushionsRangeCombo.getSelectedItem())));
        cushionsFiberTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsFiberTypeComboActionPerformed(evt);
            }
        });

        jLabel267.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel267.setText("Select Fiber Type");

        jLabel268.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel268.setText("Fiber Wastage:");

        cushionsFiberWastage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFiberWastage.setText("3");
        cushionsFiberWastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsFiberWastageActionPerformed(evt);
            }
        });

        jLabel269.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel269.setText("%");

        jLabel317.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel317.setText("Margin:");

        jLabel318.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel318.setText("Taxes:");

        cushionsTaxField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsTaxField.setText(Config.taxesRate);

        jLabel319.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel319.setText("%");

        jLabel320.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel320.setText("%");

        cushionsMarginField.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsMarginField.setText(Config.profitMargin);

        jLabel321.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel321.setText("Other costs:");

        cushionsOtherCostVal.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsOtherCostVal.setText("0.0");
        cushionsTaxField.setText(Config.taxesRate);

        javax.swing.GroupLayout cushionsCostingPanelLayout = new javax.swing.GroupLayout(cushionsCostingPanel);
        cushionsCostingPanel.setLayout(cushionsCostingPanelLayout);
        cushionsCostingPanelLayout.setHorizontalGroup(
            cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel258)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cushionsCostingPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cushionsUseCustom)
                    .addComponent(cushionsCustomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cushionsSizeLable)
                            .addComponent(jLabel265)
                            .addComponent(jLabel262)
                            .addComponent(jLabel268)
                            .addComponent(jLabel267)
                            .addComponent(jLabel259)
                            .addComponent(jLabel318)
                            .addComponent(jLabel317)
                            .addComponent(jLabel321))
                        .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                                        .addComponent(cushionsTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel319))
                                    .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                                        .addComponent(cushionsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel320))
                                    .addComponent(cushionsOtherCostVal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cushionsCostingPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                                        .addComponent(cushionsFiberWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel269))
                                    .addComponent(cushionsSizeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cushionsFabricTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                                        .addComponent(cushionsFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel260))
                                    .addComponent(cushionsRangeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cushionsFiberTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cushionsCustomFiberButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cushionsCostingPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(cushionsNewCostingButton)
                                    .addComponent(cushionsSubmitButton))
                                .addGap(169, 169, 169)))))
                .addGap(14, 14, 14))
        );
        cushionsCostingPanelLayout.setVerticalGroup(
            cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel258)
                .addGap(18, 18, 18)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel259)
                    .addComponent(cushionsRangeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cushionsFabricTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel265))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cushionsSizeLable)
                    .addComponent(cushionsSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel262)
                    .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(cushionsCostingPanelLayout.createSequentialGroup()
                            .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cushionsFabricWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel260))
                            .addGap(24, 24, 24))
                        .addComponent(cushionsCustomFiberButton)))
                .addGap(2, 2, 2)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel267)
                    .addComponent(cushionsFiberTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel268)
                    .addComponent(cushionsFiberWastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel269))
                .addGap(18, 18, 18)
                .addComponent(cushionsUseCustom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cushionsCustomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cushionsMarginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel320)
                    .addComponent(jLabel317))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel319)
                    .addComponent(cushionsTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel318))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cushionsCostingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel321)
                    .addComponent(cushionsOtherCostVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(cushionsSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cushionsNewCostingButton))
        );

        cushionsCustomPanel.setVisible(false);
        cushionsNewCostingButton.setVisible(false);

        jLabel240.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel240.setText("SMV Value:");

        jLabel241.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel241.setText("Production Parameters");

        jLabel242.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel242.setText("Fabric Cutting Width & Height:");

        jLabel243.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel243.setText("Fiber Weight");

        cushionsFiberWeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFiberWeight.setText("0.00");

        cushionsSMVValue.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsSMVValue.setText("0.00");

        cushionsFabricCutWidthHeight.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFabricCutWidthHeight.setText("0.00");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel241)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel243)
                    .addComponent(jLabel240)
                    .addComponent(jLabel242))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cushionsFabricCutWidthHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cushionsSMVValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cushionsFiberWeight, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel241, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(cushionsFabricCutWidthHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsFiberWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsSMVValue))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel242)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel243)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel240)))
                .addGap(37, 37, 37))
        );

        jLabel244.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel244.setText("PE Bag Cost:");

        jLabel245.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel245.setText("Cost Per Unit");

        jLabel248.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel248.setText("Thread Cost:");

        jLabel249.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel249.setText("Labour Cost:");

        cushionsLabourCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsLabourCost.setText("0.00");

        cushionsFiberCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFiberCost.setText("0.00");

        cushionsThreadCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsThreadCost.setText("0.00");

        cushionsTagCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsTagCost.setText("0.00");

        cushionsLableCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsLableCost.setText("0.00");

        jLabel251.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel251.setText("POH:");

        jLabel252.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel252.setText("Toatal Cost Per Unit:");

        jLabel253.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel253.setText("Tag Cost:");

        jLabel254.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel254.setText("Total Material Cost");

        cushionsPOH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsPOH.setText("0.00");

        jLabel255.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel255.setText("Fiber Cost:");

        jLabel256.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel256.setText("Lable Cost:");

        cushionsPEBagCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsPEBagCost.setText("0.00");

        cushionsTotalMaterialCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cushionsTotalMaterialCost.setText("0.00");

        cushionsFabricCost.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cushionsFabricCost.setText("0.00");

        jLabel257.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel257.setText("Fabric Cost:");

        cushionsToatalCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cushionsToatalCost.setText("0.00");

        jLabel346.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel346.setText("Net Selling Price:");

        jLabel347.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel347.setText("Taxes:");

        jLabel348.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel348.setText("Gross Selling Price:");

        cushionsNetSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cushionsNetSellingPrice.setText("0.00");

        cushionsTaxes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cushionsTaxes.setText("0.00");

        cushionsGrossSellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cushionsGrossSellingPrice.setText("0.00");

        cushionsExportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/export.png"))); // NOI18N
        cushionsExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cushionsExportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(cushionsExportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel245))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel42Layout.createSequentialGroup()
                                .addComponent(jLabel348)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cushionsGrossSellingPrice))
                            .addGroup(jPanel42Layout.createSequentialGroup()
                                .addComponent(jLabel347)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cushionsTaxes))
                            .addGroup(jPanel42Layout.createSequentialGroup()
                                .addComponent(jLabel346)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cushionsNetSellingPrice))
                            .addGroup(jPanel42Layout.createSequentialGroup()
                                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel254)
                                    .addComponent(jLabel251)
                                    .addComponent(jLabel252)
                                    .addComponent(jLabel249)
                                    .addComponent(jLabel244)
                                    .addComponent(jLabel253)
                                    .addComponent(jLabel256)
                                    .addComponent(jLabel255)
                                    .addComponent(jLabel257)
                                    .addComponent(jLabel248))
                                .addGap(202, 202, 202)
                                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cushionsToatalCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsFabricCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsTotalMaterialCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsLableCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsTagCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsPOH, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsFiberCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsLabourCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsPEBagCost, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cushionsThreadCost, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cushionsExportButton)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel245, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(cushionsFabricCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsFiberCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsThreadCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsLableCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsTagCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsPEBagCost)
                        .addGap(11, 11, 11)
                        .addComponent(cushionsTotalMaterialCost)
                        .addGap(19, 19, 19)
                        .addComponent(cushionsPOH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cushionsLabourCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cushionsToatalCost))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(jLabel257)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel255)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel248)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel256)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel253)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel244)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel254)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel251)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel249)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel252)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel346)
                    .addComponent(cushionsNetSellingPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel347)
                    .addComponent(cushionsTaxes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel348)
                    .addComponent(cushionsGrossSellingPrice))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cushionsCPUPanelLayout = new javax.swing.GroupLayout(cushionsCPUPanel);
        cushionsCPUPanel.setLayout(cushionsCPUPanelLayout);
        cushionsCPUPanelLayout.setHorizontalGroup(
            cushionsCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cushionsCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cushionsCPUPanelLayout.setVerticalGroup(
            cushionsCPUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cushionsCPUPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cushionsCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cushionsCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cushionsCostingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addComponent(cushionsCPUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cushionsCPUPanel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void cushionsRangeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsRangeComboActionPerformed
        cushionsFabricTypeCombo.setModel(new DefaultComboBoxModel(PillowLogic.getMaterialTypes((String) cushionsRangeCombo.getSelectedItem())));
        cushionsSizeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getCushionSizes((String) cushionsRangeCombo.getSelectedItem())));
        if (!cushionsCustomFiberButton.isSelected()) {
            cushionsFiberTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getFiberTypes((String) cushionsRangeCombo.getSelectedItem())));
        }
}//GEN-LAST:event_cushionsRangeComboActionPerformed

    private void cushionsFabricWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsFabricWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cushionsFabricWastageActionPerformed

    private void cushionsFabricTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsFabricTypeComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cushionsFabricTypeComboActionPerformed

    private void cushionsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsSubmitButtonActionPerformed
        CushionsViewModel cCost = new CushionsViewModel();

        String cushionsRange = (String) cushionsRangeCombo.getSelectedItem();
        cCost.setProductRange(cushionsRange);

        String fabricType = (String) cushionsFabricTypeCombo.getSelectedItem();
        cCost.setMaterialType(fabricType);

        String size = (String) cushionsSizeCombo.getSelectedItem();
        cCost.setSize(size);

        try {
            double fabricWastage = Double.parseDouble(cushionsFabricWastage.getText());
            if (fabricWastage < 0 || fabricWastage > 10) {
                JOptionPane.showMessageDialog(this, "Fabric wastage should be between 0 and 10 %");
                return;
            }
            cCost.setFabricWastage(fabricWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid fabric wastage value");
            return;
        }


        try {
            double fiberWeight = Double.parseDouble(cushionsCustomFiberWeight.getText());
            if (fiberWeight < 0.0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid custom fiber weight");
                return;
            }
            cCost.setCustomeFiberWeight(fiberWeight);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid custom fiber weight");
            return;
        }

        try {
            double otherCost = Double.parseDouble(cushionsOtherCostVal.getText());
            if (otherCost < 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid value for other costs");
                return;
            }
            cCost.setOtherCost(otherCost);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid value for other costs");
            return;
        }

        String fiberType = (String) cushionsFiberTypeCombo.getSelectedItem();
        cCost.setFiberType(fiberType);

        try {
            double fiberWastage = Double.parseDouble(cushionsFiberWastage.getText());
            if (fiberWastage < 0 || fiberWastage > 10) {
                JOptionPane.showMessageDialog(this, "Fiber wastage should be between 0 and 10 %");
                return;
            }
            cCost.setFiberWastage(fiberWastage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid fiber wastage value");
            return;
        }

        try {
            double margin = Double.parseDouble(cushionsMarginField.getText());
            if (margin < 0) {
                JOptionPane.showMessageDialog(this, "Profit margin should be a positive value");
                return;
            }
            cCost.setMargin(margin);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid margin value");
            return;
        }

        try {
            double taxRate = Double.parseDouble(cushionsTaxField.getText());
            if (taxRate < 0) {
                JOptionPane.showMessageDialog(this, "Tax rate should be a positive value");
                return;
            }
            cCost.setTaxRate(taxRate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid tax rate value");
            return;
        }

        boolean useCustom = cushionsUseCustom.isSelected();
        if (useCustom) {
            cCost.setIsCustom(useCustom);
            try {
                Double widthHeight = Double.parseDouble(cushionsCustomWidthHeight.getText());
                if (widthHeight <= 0 || widthHeight > 120) {
                    JOptionPane.showMessageDialog(this, "Width & Height should be between 0 and 120");
                    return;
                }
                cCost.setCustomWidthHeight(widthHeight);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid width value");
                return;
            }

            cCost.setIncludeLable(cushionsIncludeLable.isSelected());
            cCost.setIncludeTag(cushionsIncludeTag.isSelected());
            cCost.setIncludePEBag(cushionsIncludePEBag.isSelected());
        }
        DecimalFormat format = new DecimalFormat();
        format.setMaximumFractionDigits(2);
        format.setMinimumFractionDigits(2);

        CushionsViewModel cReturn = CushionLogic.getCostPerUnit(cCost);
        cushionsFabricCost.setText(format.format(cReturn.getFabricCost()) + "");
        cushionsFiberCost.setText(format.format(cReturn.getFiberCost()) + "");
        cushionsThreadCost.setText(format.format(cReturn.getThreadCost()) + "");
        cushionsLableCost.setText(format.format(cReturn.getLableCost()) + "");
        cushionsTagCost.setText(format.format(cReturn.getTagCost()) + "");
        cushionsPEBagCost.setText(format.format(cReturn.getPEBagCost()) + "");
        cushionsTotalMaterialCost.setText(format.format(cReturn.getTotalMaterialCost()) + "");
        cushionsPOH.setText(format.format(cReturn.getPohCost()) + "");
        cushionsLabourCost.setText(format.format(cReturn.getLabourCost()) + "");
        cushionsToatalCost.setText(format.format(cReturn.getTotalCost()) + "");
        cushionsFabricCutWidthHeight.setText(format.format(cReturn.getFabricCuttingWidthHeight()) + "");
        cushionsFiberWeight.setText(format.format(cReturn.getFiberWeight()) + "");
        cushionsSMVValue.setText(format.format(cReturn.getSmvValue()) + "");
        cushionsNetSellingPrice.setText(format.format(cReturn.getNetSellingPrice()));
        cushionsTaxes.setText(format.format(cReturn.getTaxes()));
        cushionsGrossSellingPrice.setText(format.format(cReturn.getGrossSellingPrice()));

        //export model
        model = new ExportModel();
        model.setProductName("Cushion");
        model.setProductRange(cReturn.getProductRange());
        if (cReturn.isIsCustom()) {
            model.setProductSize(cReturn.getCustomWidthHeight() + "X" + cReturn.getCustomWidthHeight());
        } else {
            model.setProductSize(cReturn.getSize());
        }
        model.setTotalMaterialCost(cReturn.getTotalMaterialCost());
        model.setLabourCost(cReturn.getLabourCost());
        model.setProductionOverHead(cReturn.getPohCost());
        model.setTotalCostPerUnit(cReturn.getTotalCost());
        model.setNetSellingPrice(cReturn.getNetSellingPrice());
        model.setTaxes(cReturn.getTaxes());
        model.setGrossSellingPrice(cReturn.getGrossSellingPrice());

//        cushionsRangeCombo.setEnabled(false);
//        cushionsFabricTypeCombo.setEnabled(false);
//        cushionsSizeCombo.setEnabled(false);
//        cushionsFabricWastage.setEnabled(false);
//        cushionsCustomFiberButton.setEnabled(false);
//        cushionsFiberTypeCombo.setEnabled(false);
//        cushionsFiberWastage.setEnabled(false);
//        cushionsUseCustom.setEnabled(false);
//        cushionsCustomWidthHeight.setEnabled(false);
//        cushionsIncludeLable.setEnabled(false);
//        cushionsIncludePEBag.setEnabled(false);
//        cushionsIncludeTag.setEnabled(false);
//        cushionsMarginField.setEnabled(false);
//        cushionsTaxField.setEnabled(false);
//
//        cushionsSubmitButton.setVisible(false);
//        cushionsNewCostingButton.setVisible(true);
        cushionsCPUPanel.setVisible(true);
    }//GEN-LAST:event_cushionsSubmitButtonActionPerformed

    private void cushionsUseCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsUseCustomActionPerformed
        if (cushionsUseCustom.isSelected()) {
            cushionsCustomPanel.setVisible(true);
            cushionsSizeCombo.setVisible(false);
            cushionsSizeLable.setVisible(false);
        } else {
            cushionsCustomPanel.setVisible(false);
            cushionsSizeCombo.setVisible(true);
            cushionsSizeLable.setVisible(true);
        }
}//GEN-LAST:event_cushionsUseCustomActionPerformed

    private void cushionsNewCostingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsNewCostingButtonActionPerformed
        cushionsRangeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getProductRanges()));
        cushionsFabricTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getMaterialTypes(
                (String) cushionsRangeCombo.getSelectedItem())));
        cushionsSizeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getCushionSizes(
                (String) cushionsRangeCombo.getSelectedItem())));
        cushionsFabricWastage.setText("3");
        cushionsCustomFiberButton.setSelected(false);
        cushionsFiberTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getFiberTypes(
                (String) cushionsRangeCombo.getSelectedItem())));
        cushionsFiberWastage.setText("3");
        cushionsUseCustom.setSelected(false);
        cushionsCustomPanel.setVisible(false);
        cushionsCustomWidthHeight.setText("");
        cushionsIncludeLable.setSelected(false);
        cushionsIncludePEBag.setSelected(false);
        cushionsIncludeTag.setSelected(false);

        cushionsRangeCombo.setEnabled(true);
        cushionsFabricTypeCombo.setEnabled(true);
        cushionsSizeCombo.setEnabled(true);
        cushionsFabricWastage.setEnabled(true);
        cushionsCustomFiberButton.setEnabled(true);
        cushionsFiberTypeCombo.setEnabled(true);
        cushionsFiberWastage.setEnabled(true);
        cushionsUseCustom.setEnabled(true);
        cushionsCustomWidthHeight.setEnabled(true);
        cushionsIncludeLable.setEnabled(true);
        cushionsIncludePEBag.setEnabled(true);
        cushionsIncludeTag.setEnabled(true);
        cushionsMarginField.setEnabled(true);
        cushionsTaxField.setEnabled(true);

        cushionsSubmitButton.setVisible(true);
        cushionsNewCostingButton.setVisible(false);
        cushionsCPUPanel.setVisible(false);

        //nulling the model
        model = null;
}//GEN-LAST:event_cushionsNewCostingButtonActionPerformed

    private void cushionsCustomFiberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsCustomFiberButtonActionPerformed
        if (cushionsCustomFiberButton.isSelected()) {
            cushionsFiberTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getFiberTypes()));
        } else {
            cushionsFiberTypeCombo.setModel(new DefaultComboBoxModel(CushionLogic.getFiberTypes((String) cushionsRangeCombo.getSelectedItem())));
        }
}//GEN-LAST:event_cushionsCustomFiberButtonActionPerformed

    private void cushionsFiberTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsFiberTypeComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cushionsFiberTypeComboActionPerformed

    private void cushionsFiberWastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsFiberWastageActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cushionsFiberWastageActionPerformed

    private void cushionsExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cushionsExportButtonActionPerformed
        if (model != null) {
            Export export = new Export(model);
            export.openFile();
        }
}//GEN-LAST:event_cushionsExportButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cushionsCPUPanel;
    private javax.swing.JPanel cushionsCostingPanel;
    private javax.swing.JRadioButton cushionsCustomFiberButton;
    private javax.swing.JTextField cushionsCustomFiberWeight;
    private javax.swing.JPanel cushionsCustomPanel;
    private javax.swing.JTextField cushionsCustomWidthHeight;
    private javax.swing.JButton cushionsExportButton;
    private javax.swing.JLabel cushionsFabricCost;
    private javax.swing.JLabel cushionsFabricCutWidthHeight;
    private javax.swing.JComboBox cushionsFabricTypeCombo;
    private javax.swing.JTextField cushionsFabricWastage;
    private javax.swing.JLabel cushionsFiberCost;
    private javax.swing.JComboBox cushionsFiberTypeCombo;
    private javax.swing.JTextField cushionsFiberWastage;
    private javax.swing.JLabel cushionsFiberWeight;
    private javax.swing.JLabel cushionsGrossSellingPrice;
    private javax.swing.JRadioButton cushionsIncludeLable;
    private javax.swing.JRadioButton cushionsIncludePEBag;
    private javax.swing.JRadioButton cushionsIncludeTag;
    private javax.swing.JLabel cushionsLableCost;
    private javax.swing.JLabel cushionsLabourCost;
    private javax.swing.JTextField cushionsMarginField;
    private javax.swing.JLabel cushionsNetSellingPrice;
    private javax.swing.JButton cushionsNewCostingButton;
    private javax.swing.JTextField cushionsOtherCostVal;
    private javax.swing.JLabel cushionsPEBagCost;
    private javax.swing.JLabel cushionsPOH;
    private javax.swing.JComboBox cushionsRangeCombo;
    private javax.swing.JLabel cushionsSMVValue;
    private javax.swing.JComboBox cushionsSizeCombo;
    private javax.swing.JLabel cushionsSizeLable;
    private javax.swing.JButton cushionsSubmitButton;
    private javax.swing.JLabel cushionsTagCost;
    private javax.swing.JTextField cushionsTaxField;
    private javax.swing.JLabel cushionsTaxes;
    private javax.swing.JLabel cushionsThreadCost;
    private javax.swing.JLabel cushionsToatalCost;
    private javax.swing.JLabel cushionsTotalMaterialCost;
    private javax.swing.JRadioButton cushionsUseCustom;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel348;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new CushionsCostingPanel());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
}
